# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ruck-midi}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tom Lieber"]
  s.date = %q{2010-07-25}
  s.default_executable = %q{ruck_midi}
  s.description = %q{      Real-time and offline ruck shredulers for MIDI using midiator and midilib.
}
  s.email = %q{tom@alltom.com}
  s.executables = ["ruck_midi"]
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "README",
     "Rakefile",
     "VERSION",
     "bin/ruck_midi",
     "examples/ex01.rb",
     "examples/ex02.rb",
     "lib/ruck/midi.rb",
     "lib/ruck/midi/midi.rb",
     "ruck-midi.gemspec"
  ]
  s.homepage = %q{http://github.com/alltom/ruck-midi}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{real-time and offline ruck shredulers for MIDI (thanks midiator and midilib)}
  s.test_files = [
    "examples/ex01.rb",
     "examples/ex02.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ruck>, [">= 0"])
      s.add_runtime_dependency(%q<midiator>, [">= 0"])
      s.add_runtime_dependency(%q<midilib>, [">= 0"])
    else
      s.add_dependency(%q<ruck>, [">= 0"])
      s.add_dependency(%q<midiator>, [">= 0"])
      s.add_dependency(%q<midilib>, [">= 0"])
    end
  else
    s.add_dependency(%q<ruck>, [">= 0"])
    s.add_dependency(%q<midiator>, [">= 0"])
    s.add_dependency(%q<midilib>, [">= 0"])
  end
end

